apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # Using ClusterSecretStore for broader access, can be SecretStore if namespaced
metadata:
  name: dev-azure-kv # Name of the ClusterSecretStore
spec:
  provider:
    azurekv:
      tenantId: "YOUR_AZURE_TENANT_ID" # Replace with your Azure Tenant ID
      vaultUrl: "https://YOUR_DEV_KEY_VAULT_NAME.vault.azure.net" # Replace with your Key Vault URL
      # authType: WorkloadIdentity # Recommended
      # serviceAccountRef:
      #   name: external-secrets-sa # The service account name that ESO controller is running under (if using Workload Identity)
      #   namespace: external-secrets # The namespace of the ESO controller SA
      # ---- OR ----
      # If not using Workload Identity (less secure, relies on AKS Managed Identity with Key Vault access)
      # authType: ManagedIdentity
      # identityId: "YOUR_AKS_MANAGED_IDENTITY_CLIENT_ID" # Client ID of the AKS Kubelet identity (usually) or a User Assigned Identity with KV access
      # For User Assigned Identity, ensure it's associated with VMSS of agent pools & has KV access policies. 