apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability-tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      storage:
        trace:
          backend: azure
          azure:
            storage_account_name: "sttempoobsopsuaen001"
            storage_account_key: $(AZURE_STORAGE_KEY)

    # Use the secret created by External Secrets Operator
    envFrom:
      - secretRef:
          name: tempo-storage-secret
