apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: flux-system
spec:
  interval: 5m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts 