apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  # The namespace here is important. It's where the HelmRelease custom resource itself will reside.
  # For base definitions, it's common to put them in the target deployment namespace.
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0" # Base version, can be overridden by cluster-specific patch
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx # Assumes HelmRepository 'ingress-nginx' exists in flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2 # Base replica count
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
        # type: LoadBalancer
      metrics:
        enabled: true
      admissionWebhooks:
        patch:
          nodeSelector:
            kubernetes.io/os: linux
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: linux 