apiVersion: v1
kind: Namespace
metadata:
  name: dev-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager 