apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-storage-creds
  namespace: observability-loki
spec:
  secretStoreRef:
    name: dev-akv-secretstore
    kind: ClusterSecretStore
  target:
    name: loki-storage-secret
  data:
  - secretKey: AZURE_STORAGE_KEY
    remoteRef:
      key: ops-uaenorth-loki-storage-key
