apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability-loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      auth_enabled: false
      storage:
        type: "azure"
        azure:
          account_name: "stlokiobsopsuaen001"
          account_key: $(AZURE_STORAGE_KEY) # Value comes from the secret
    
    # Use the secret created by External Secrets Operator
    envFrom:
      - secretRef:
          name: loki-storage-secret
