apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager # Target deployment namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.5" # Base version
      sourceRef:
        kind: HelmRepository
        name: jetstack # Assumes HelmRepository 'jetstack' exists in flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    installCRDs: true
    nodeSelector:
      kubernetes.io/os: linux
    prometheus:
      enabled: true 