apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux-config/clusters/platform-core-dev-aks/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 