# This is a placeholder SecretStore for Azure Key Vault for the dev cluster.
# Replace with your actual Key Vault details.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev-azure-kv
  # namespace: external-secrets # Not needed for ClusterSecretStore
spec:
  provider:
    azure:
      tenantId: "909b0a4b-54de-4250-b223-b55c49dabac7" # Replace with your Azure Tenant ID
      vaultUrl: "https://platform-core-dev-kv.vault.azure.net" # Replace with your Key Vault URL
      authType: "WorkloadIdentity" # Or ServicePrincipal, ManagedIdentity
      # If using WorkloadIdentity:
      serviceAccountRef:
        name: external-secrets # Ensure this ServiceAccount exists and is federated with Azure AD
        namespace: external-secrets
      # If using ServicePrincipal:
      # authSecretRef:
      #   clientId:
      #     name: azure-credentials # K8s secret holding client ID
      #     key: clientId
      #   clientSecret:
      #     name: azure-credentials # K8s secret holding client secret
      #     key: clientSecret 