# This is a placeholder SecretStore for Azure Key Vault for the dev cluster.
# Replace with your actual Key Vault details.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-store # You can choose a descriptive name for your store
  # namespace: external-secrets # Not needed for ClusterSecretStore
spec:
  provider:
    azure:
      # Replace with your Key Vault's URL
      vaultUrl: "https://platform-core-dev-kv.vault.azure.net/"
      # Replace with your Azure Tenant ID
      tenantId: "909b0a4b-54de-4250-b223-b55c49dabac7"
      # Use WorkloadIdentity for authentication
      authType: "WorkloadIdentity"
      # The specific identity (Client ID) is typically derived from the
      # annotations on the External Secrets Operator's service account when
      # authType is WorkloadIdentity. No explicit serviceAccountRef or identityId
      # is usually needed here if ESO's own SA is annotated for workload identity.
      # If using WorkloadIdentity:
      # serviceAccountRef:
      #   name: external-secrets # Ensure this ServiceAccount exists and is federated with Azure AD
      #   namespace: external-secrets
      # If using ServicePrincipal:
      # authSecretRef:
      #   clientId:
      #     name: azure-credentials # K8s secret holding client ID
      #     key: clientId
      #   clientSecret:
      #     name: azure-credentials # K8s secret holding client secret
      #     key: clientSecret 